return {
    
    "nvimdev/lspsaga.nvim",
    event = "LspAttach",
    enabled = require("config.util").is_enabled("nvimdev/lspsaga.nvim"),
    -- enabled = false,
    config = function()
      require("lspsaga").setup {
        definition = {
          edit = "<C-c>o",
          vsplit = "<C-c>v",
          split = "<C-c>i",
          table = "<C-c>t",
          quit = "q",
        },
        code_action = {
          num_shortcut = true,
          show_server_name = false,
          extend_gitsigns = true,
          keys = {
            -- string | table type
            quit = "q",
            exec = "<CR>",
          },
        },
        lightbulb = {
          enable = true,
          enable_in_insert = true,
          sign = true,
          sign_priority = 40,
          virtual_text = true,
        },
        diagnostic = {
          on_insert = false,
          on_insert_follow = false,
          insert_winblend = 0,
          show_code_action = true,
          show_source = true,
          jump_num_shortcut = true,
          max_width = 0.7,
          max_height = 0.6,
          max_show_width = 0.9,
          max_show_height = 0.6,
          text_hl_follow = true,
          border_follow = true,
          extend_relatedInformation = false,
          keys = {
            exec_action = "o",
            quit = "q",
            expand_or_jump = "<CR>",
            quit_in_show = { "q", "<ESC>" },
          },
        },
        hover = {
          max_width = 0.6,
          open_link = "gx",
          open_browser = "!chrome",
        },
        rename = {
          quit = "<C-c>",
          exec = "<CR>",
          mark = "x",
          confirm = "<CR>",
          in_select = true,
        },
        outline = {
          win_position = "right",
          win_with = "",
          win_width = 30,
          preview_width = 0.4,
          show_detail = true,
          auto_preview = true,
          auto_refresh = true,
          auto_close = true,
          auto_resize = false,
          custom_sort = nil,
          keys = {
            expand_or_jump = "o",
            quit = "q",
          },
        },
        callhierarchy = {
          show_detail = false,
          keys = {
            edit = "e",
            vsplit = "s",
            split = "i",
            table = "t",
            jump = "o",
            quit = "q",
            expand_collapse = "u",
          },
        },
        beacon = {
          enable = true,
          frequency = 7,
        },
        ui = {
          -- This option only works in Neovim 0.9
          title = true,
          -- Border type can be single, double, rounded, solid, shadow.
          border = "single",
          winblend = 0,
          expand = "",
          collapse = "",
          code_action = "💡",
          incoming = " ",
          outgoing = " ",
          hover = " ",
          kind = {
            File = { "󰈔 ", "LspKindFile" },
            Module = { " ", "LspKindModule" },
            Namespace = { " ", "LspKindNamespace" },
            Package = { " ", "LspKindPackage" },
            Class = { " ", "LspKindClass" },
            Method = { " ", "LspKindMethod" },
            Property = { " ", "LspKindProperty" },
            Field = { " ", "LspKindField" },
            Constructor = { " ", "LspKindConstructor" },
            Enum = { " ", "LspKindEnum" },
            Interface = { " ", "LspKindInterface" },
            Function = { "󰊕 ", "LspKindFunction" },
            Variable = { " ", "LspKindVariable" },
            Constant = { " ", "LspKindConstant" },
            String = { " ", "LspKindString" },
            Number = { "󰉻 ", "LspKindNumber" },
            Boolean = { " ", "LspKindBoolean" },
            Array = { " ", "LspKindArray" },
            Object = { "󰐾 ", "LspKindObject" },
            Key = { "󰌋 ", "LspKindKey" },
            Null = { "󰟢 ", "LspKindNull" },
            EnumMember = { " ", "LspKindEnumMember" },
            Struct = { " ", "LspKindStruct" },
            Event = { " ", "LspKindEvent" },
            Operator = { " ", "LspKindOperator" },
            TypeParameter = { " ", "LspKindTypeParameter" },
            TypeAlias = { " ", "LspKindTypeAlias" },
            Parameter = { " ", "LspKindParameter" },
            StaticMethod = { " ", "LspKindStaticMethod" },
            Macro = { " ", "LspKindMacro" },
            Text = { " ", "LspKindText" },
            Snippet = { " ", "LspKindSnippet" },
            Folder = { " ", "LspKindFolder" },
            Unit = { " ", "LspKindUnit" },
            Value = { " ", "LspKindValue" },
          },
        },
      }
    end,
    dependencies = {
      { "nvim-tree/nvim-web-devicons" },
      --Please make sure you install markdown and markdown_inline parser
      { "nvim-treesitter/nvim-treesitter" },
    },
  }

