return {
  lsp = { -- {{{
    diagnostic = {
      signs = {
        Error = "🔥",
        Warn = "💩",
        Info = "💬",
        Hint = "💡",
      },
      upper_signs = {
        -- We don't want to calculate these on the fly.
        ERROR = "🔥",
        WARN = "💩",
        INFO = "💬",
        HINT = "💡",
      },
    },
  }, -- }}}
    kind = {
      Array = "[]",
      Boolean = " ",
      Calendar = " ",
      Class = "󰠱 ",
      Codeium = " ",
      Color = "󰏘 ",
      Constant = "󰏿 ",
      Constructor = " ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = "󰜢 ",
      File = "󰈚 ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Keyword = "󰌋 ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = "󰅩 ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = "󰙅 ",
      Table = " ",
      TabNine = "",
      Tag = " ",
      Text = "󰉿 ",
      TypeParameter = "󰊄 ",
      Unit = "󰑭 ",
      Value = "󰎠 ",
      Variable = "󰀫 ",
    },
    git = {
      LineAdded = " ",
      LineModified = " ",
      LineRemoved = " ",
      FileDeleted = " ",
      FileIgnored = "◌",
      FileRenamed = " ",
      FileStaged = "S",
      FileUnmerged = " ",
      FileUnstaged = "",
      FileUntracked = "U",
      Diff = " ",
      Repo = " ",
      Octoface = " ",
      Branch = "",
    },
    ui = {
      ArrowCircleDown = "",
      ArrowCircleLeft = "",
      ArrowCircleRight = "",
      ArrowCircleUp = "",
      BoldArrowDown = "",
      BoldArrowLeft = "",
      BoldArrowRight = "",
      BoldArrowUp = "",
      BoldClose = "",
      BoldDividerLeft = "",
      BoldDividerRight = "",
      BoldLineLeft = "▎",
      BookMark = "",
      BoxChecked = "",
      Bug = " ",
      Stacks = " ",
      Scopes = "",
      Watches = "",
      DebugConsole = " ",
      Calendar = " ",
      Check = " ",
      ChevronRight = ">",
      ChevronShortDown = "",
      ChevronShortLeft = "",
      ChevronShortRight = "",
      ChevronShortUp = "",
      Circle = " ",
      Close = "",
      CloudDownload = " ",
      Code = " ",
      Comment = " ",
      Dashboard = " ",
      DividerLeft = "",
      DividerRight = "",
      DoubleChevronRight = "»",
      Ellipsis = "",
      EmptyFolder = " ",
      EmptyFolderOpen = " ",
      File = " ",
      FileSymlink = " ",
      Files = " ",
      FindFile = "",
      FindText = "",
      Fire = " ",
      Folder = "",
      FolderOpen = "",
      FolderSymlink = "",
      Forward = "",
      Gear = " ",
      History = " ",
      Lightbulb = " ",
      LineLeft = "▏",
      LineMiddle = "│",
      List = " ",
      Lock = " ",
      NewFile = " ",
      Note = " ",
      Package = " ",
      Pencil = "",
      Plus = "",
      Project = " ",
      Search = " ",
      SignIn = " ",
      SignOut = " ",
      Tab = " ",
      Table = " ",
      Target = " ",
      Telescope = " ",
      Text = "",
      Tree = "",
      Triangle = "契",
      TriangleShortArrowDown = "",
      TriangleShortArrowLeft = "",
      TriangleShortArrowRight = "",
      TriangleShortArrowUp = "",
    },
    diagnostics = {
      BoldError = "",
      Error = "🚨",
      Warn = "🤡",
      Warning = " ",
      Info = "💬",
      Information = " ",
      BoldQuestion = "",
      Question = " ",
      BoldHint = "",
      Hint = "ﯦ ",
      Debug = " ",
      Trace = "✎",
    },
    dap = {
      Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
      Breakpoint = " ",
      BreakpointCondition = " ",
      BreakpointRejected = { " ", "DiagnosticError" },
      LogPoint = ".>",
    },
    misc = {
      Robot = "ﮧ ",
      Squirrel = " ",
      Tag = " ",
      Watch = " ",
      Smiley = " ",
      Package = " ",
      CircuitBoard = " ",
    },
    border_chars = {
      border_chars_none = { "", "", "", "", "", "", "", "" },
      border_chars_empty = { " ", " ", " ", " ", " ", " ", " ", " " },
      border_chars_tmux = { " ", " ", " ", " ", " ", " ", " ", " " },
      border_chars_inner_thick = { " ", "▄", " ", "▌", " ", "▀", " ", "▐" },
      border_chars_outer_thick = { "▛", "▀", "▜", "▐", "▟", "▄", "▙", "▌" },
      border_chars_outer_thin = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
      border_chars_inner_thin = { " ", "▁", " ", "▏", " ", "▔", " ", "▕" },
      border_chars_outer_thin_telescope = { "▔", "▕", "▁", "▏", "🭽", "🭾", "🭿", "🭼" },
      border_chars_outer_thick_telescope = { "▀", "▐", "▄", "▌", "▛", "▜", "▟", "▙" },
    },
    border_fn = function(hl)
      return {
        { "╭", hl },
        { "─", hl },
        { "╮", hl },
        { "│", hl },
        { "╯", hl },
        { "─", hl },
        { "╰", hl },
        { "│", hl },
      }
    end,
  }
  